# Generated by Django 5.0.2 on 2024-02-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('translation', models.TextField()),
                ('transcription', models.TextField()),
                ('transliteration', models.TextField()),
                ('audio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
