# Generated by Django 5.0.2 on 2024-02-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('wrong_answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lessons')),
            ],
        ),
    ]
